# Generated by Django 5.0.6 on 2025-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[("C", "Compeleted"), ("P", "Pending"), ("NC", "Not-Checked")],
                default="NC",
                max_length=255,
            ),
        ),
    ]
