# Generated by Django 5.0.6 on 2024-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='status',
            field=models.CharField(choices=[('C', 'Checked'), ('NC', 'Not-Checked')], default='C', max_length=255),
        ),
    ]
