# Generated by Django 5.0.6 on 2025-03-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productcomment_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="unit_price",
            new_name="amount",
        ),
    ]
