# Generated by Django 5.0.6 on 2025-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_unit_price_product_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.FloatField(),
        ),
    ]
